const barData = {
  "venue": {
    "name": "Bar RenewK",
    "new_customer_offer": {
      "options": [
        {"id": "opt_a", "label": "30ml优质酒体验", "description": "威士忌/金酒/干邑三选一", "icon": "🥃"},
        {"id": "opt_b", "label": "第二杯半价", "description": "与朋友分享更划算", "icon": "🥂"}
      ],
      "rule": "if user_wants_pure_spirits → opt_a; if social_occasion → opt_b"
    }
  },

  "selection_flow": {
    "steps": [
      {
        "step": 1,
        "title": "今晚想怎么喝？",
        "subtitle": "选择你喜欢的口感基调",
        "type": "single_choice",
        "options": [
          {"id": "base_bubbly", "label": "清爽气泡", "icon": "🫧", "description": "带气、解渴、轻松易饮", "volume": "约 300ml", "glass": "highball"},
          {"id": "base_sour", "label": "酸爽利口", "icon": "🍋", "description": "酸甜明亮、经典结构", "volume": "约 100-150ml", "glass": "coupe"},
          {"id": "base_deep", "label": "醇厚深邃", "icon": "🥃", "description": "浓郁复杂、小口慢品", "volume": "约 100-150ml", "glass": "rocks"},
          {"id": "base_floral", "label": "花香果趣", "icon": "🌸", "description": "香气突出、甜美柔和", "volume": "约 100-150ml", "glass": "coupe"}
        ]
      },
      {
        "step": 2,
        "title": "想尝到什么味道？",
        "subtitle": "可多选，不选也可以",
        "type": "multi_choice",
        "options": [
          {"id": "lime", "label": "青柠", "icon": "🍋‍🟩"},
          {"id": "grapefruit", "label": "西柚", "icon": "🍊"},
          {"id": "pineapple", "label": "菠萝", "icon": "🍍"},
          {"id": "apple", "label": "苹果", "icon": "🍏"},
          {"id": "green_grape", "label": "青提", "icon": "🍇"},
          {"id": "chrysanthemum", "label": "菊花", "icon": "🏵️"},
          {"id": "elderflower", "label": "接骨木花", "icon": "🌼"},
          {"id": "violet", "label": "紫罗兰", "icon": "💜"},
          {"id": "lavender", "label": "薰衣草", "icon": "💜"},
          {"id": "mint", "label": "薄荷", "icon": "🌿"},
          {"id": "lemongrass", "label": "香茅", "icon": "🌾"},
          {"id": "ginger", "label": "生姜", "icon": "🫚"},
          {"id": "cinnamon", "label": "肉桂", "icon": "🥮"},
          {"id": "smoky", "label": "烟熏", "icon": "🔥"},
          {"id": "bitter", "label": "苦精", "icon": "💊"},
          {"id": "coffee", "label": "咖啡", "icon": "☕"},
          {"id": "matcha", "label": "抹茶", "icon": "🍵"},
          {"id": "white_chocolate", "label": "白巧克力", "icon": "🍫"},
          {"id": "almond", "label": "杏仁", "icon": "🥜"},
          {"id": "milk", "label": "牛奶", "icon": "🥛"},
          {"id": "earl_grey", "label": "伯爵茶", "icon": "🫖"},
          {"id": "black_cherry", "label": "黑樱桃", "icon": "🍒"},
          {"id": "cucumber", "label": "青瓜", "icon": "🥒"},
          {"id": "orange", "label": "橙子", "icon": "🍊"}
        ]
      },
      {
        "step": 3,
        "title": "想要多强的存在感？",
        "subtitle": "选择酒精度范围",
        "type": "single_choice",
        "options": [
          {"id": "strength_low", "label": "🟢 低度 (5-10°)", "description": "长饮，可以大口喝"},
          {"id": "strength_mid", "label": "🟡 中度 (15-25°)", "description": "标准鸡尾酒，小口品"},
          {"id": "strength_high", "label": "🔴 高度 (25-30°)", "description": "烈酒感强，慢慢喝"}
        ]
      }
    ]
  },

  "cocktails": [
    {
      "id": "gin_tonic",
      "name": "金汤力",
      "name_en": "Gin Tonic",
      "category": "long_drink",
      "price_range": [28, 68],
      "base_tags": ["base_bubbly"],
      "flavor_tags": ["lime"],
      "strength": "strength_low",
      "radar": {"sour": 2, "sweet": 1, "bitter": 2, "strong": 1, "fruity": 1},
      "description": "经典永不过时，金酒的草本遇见汤力水的微苦，像一阵凉爽的穿堂风。",
      "volume": "约 300ml",
      "glass": "highball"
    },
    {
      "id": "canton_gt",
      "name": "广式金汤力",
      "name_en": "Canton G&T",
      "category": "long_drink",
      "price": 48,
      "base_tags": ["base_bubbly"],
      "flavor_tags": ["chrysanthemum"],
      "strength": "strength_low",
      "radar": {"sour": 1, "sweet": 2, "bitter": 2, "strong": 1, "floral": 4},
      "description": "一杯可以喝的菊花台，清雅回甘，专解油腻。",
      "volume": "约 300ml",
      "glass": "highball"
    },
    {
      "id": "thai_gt",
      "name": "泰式金汤力",
      "name_en": "Thai G&T",
      "category": "long_drink",
      "price": 48,
      "base_tags": ["base_bubbly"],
      "flavor_tags": ["lemongrass", "pineapple"],
      "strength": "strength_low",
      "radar": {"sour": 2, "sweet": 3, "bitter": 1, "strong": 1, "fruity": 4},
      "description": "舌尖上的东南亚，香茅和菠萝把你一秒空降到普吉岛。",
      "volume": "约 300ml",
      "glass": "highball"
    },
    {
      "id": "highball",
      "name": "嗨棒",
      "name_en": "Highball",
      "category": "long_drink",
      "price_range": [28, 68],
      "base_tags": ["base_bubbly"],
      "flavor_tags": [],
      "strength": "strength_low",
      "radar": {"sour": 1, "sweet": 1, "bitter": 1, "strong": 2, "fruity": 1},
      "description": "威士忌被苏打水轻轻托起，醇香又轻盈，第一杯的最佳人选。",
      "volume": "约 300ml",
      "glass": "highball"
    },
    {
      "id": "paloma",
      "name": "帕罗玛",
      "name_en": "Paloma",
      "category": "long_drink",
      "price": 48,
      "base_tags": ["base_bubbly"],
      "flavor_tags": ["grapefruit", "lime"],
      "strength": "strength_low",
      "radar": {"sour": 3, "sweet": 2, "bitter": 2, "strong": 1, "fruity": 3},
      "description": "西柚的甜苦和梅斯卡尔的辛香在气泡里跳舞，一口入夏。",
      "volume": "约 300ml",
      "glass": "highball"
    },
    {
      "id": "gin_fizz",
      "name": "金菲士",
      "name_en": "Gin Fizz",
      "category": "long_drink",
      "price": 38,
      "base_tags": ["base_bubbly"],
      "flavor_tags": ["lime"],
      "strength": "strength_low",
      "radar": {"sour": 3, "sweet": 2, "bitter": 0, "strong": 1, "fruity": 2},
      "description": "成年人的柠檬汽水，酸得清爽，甜得节制。",
      "volume": "约 300ml",
      "glass": "highball"
    },
    {
      "id": "kaikan_fizz",
      "name": "会馆菲士",
      "name_en": "Kaikan Fizz",
      "category": "long_drink",
      "price": 48,
      "base_tags": ["base_bubbly"],
      "flavor_tags": ["milk"],
      "strength": "strength_low",
      "radar": {"sour": 2, "sweet": 3, "bitter": 0, "strong": 1, "creamy": 4},
      "description": "像一杯会冒泡的优酸乳，奶乎乎的，喝着毫无压力。",
      "volume": "约 300ml",
      "glass": "highball"
    },
    {
      "id": "bitter_melon_fizz",
      "name": "苦瓜菲士",
      "name_en": "Bitter Melon Fizz",
      "category": "long_drink",
      "price": 48,
      "base_tags": ["base_bubbly"],
      "flavor_tags": ["cucumber"],
      "strength": "strength_low",
      "radar": {"sour": 2, "sweet": 1, "bitter": 3, "strong": 1, "fruity": 2},
      "description": "苦瓜的清香被青瓜柔和，龙舌兰的香料味在底下托着，越喝越上瘾。",
      "volume": "约 300ml",
      "glass": "highball"
    },
    {
      "id": "sunshine_icetea",
      "name": "橙柚冰茶",
      "name_en": "Sunshine Icetea",
      "category": "long_drink",
      "price": 48,
      "base_tags": ["base_bubbly"],
      "flavor_tags": ["orange", "grapefruit", "earl_grey"],
      "strength": "strength_low",
      "radar": {"sour": 2, "sweet": 2, "bitter": 2, "strong": 1, "fruity": 3},
      "description": "落日时分的一杯冰茶，伯爵茶的佛手柑香和橙柚的酸甜完美混搭。",
      "volume": "约 300ml",
      "glass": "highball"
    },
    {
      "id": "jungle_bird",
      "name": "丛林鸟",
      "name_en": "Jungle Bird",
      "category": "long_drink",
      "price": 48,
      "base_tags": ["base_bubbly"],
      "flavor_tags": ["pineapple"],
      "strength": "strength_low",
      "radar": {"sour": 2, "sweet": 3, "bitter": 2, "strong": 2, "fruity": 5},
      "description": "菠萝的酸甜像热带雨林的暴雨，金巴利的微苦是雨后的泥土香。",
      "volume": "约 300ml",
      "glass": "highball"
    },
    {
      "id": "sidecar",
      "name": "边车",
      "name_en": "Sidecar",
      "category": "short_drink",
      "price_range": [48, 78],
      "base_tags": ["base_sour"],
      "flavor_tags": ["orange", "lime"],
      "strength": "strength_mid",
      "radar": {"sour": 3, "sweet": 2, "bitter": 1, "strong": 3, "fruity": 3},
      "description": "干邑的醇厚裹着柑橘的明亮，像坐着摩托边车穿过阳光下的橘园。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "between_the_sheets",
      "name": "床第之间",
      "name_en": "Between the Sheets",
      "category": "short_drink",
      "price_range": [48, 78],
      "base_tags": ["base_deep"],
      "flavor_tags": ["orange", "lime"],
      "strength": "strength_high",
      "radar": {"sour": 2, "sweet": 2, "bitter": 1, "strong": 4, "fruity": 3},
      "description": "白兰地和朗姆酒缠绵，柑橘是它们之间的暗号，浓郁又危险。",
      "volume": "约 100ml",
      "glass": "coupe"
    },
    {
      "id": "whiskey_sour",
      "name": "威士忌酸",
      "name_en": "Whiskey Sour",
      "category": "short_drink",
      "price": 48,
      "base_tags": ["base_sour"],
      "flavor_tags": ["lime"],
      "strength": "strength_mid",
      "radar": {"sour": 4, "sweet": 2, "bitter": 0, "strong": 3, "fruity": 2},
      "description": "波本威士忌和柠檬汁的黄金比例，像一颗可以喝的柠檬硬糖，永远经典。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "matchoc_sour",
      "name": "抹茶白巧威士忌酸",
      "name_en": "MatChoc Sour",
      "category": "short_drink",
      "price": 58,
      "base_tags": ["base_sour"],
      "flavor_tags": ["matcha", "white_chocolate"],
      "strength": "strength_mid",
      "radar": {"sour": 2, "sweet": 4, "bitter": 1, "strong": 3, "creamy": 4},
      "description": "白巧的丝滑先拥抱你，抹茶的清苦在尾调轻轻回甘，像液态的和果子。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "almond_sour",
      "name": "杏仁酸",
      "name_en": "Almond Sour",
      "category": "short_drink",
      "price": 48,
      "base_tags": ["base_sour"],
      "flavor_tags": ["almond"],
      "strength": "strength_mid",
      "radar": {"sour": 3, "sweet": 3, "bitter": 0, "strong": 3, "nutty": 4},
      "description": "甜而不腻，童年的露露变成了大人的快乐水。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "aperol_sour",
      "name": "阿佩罗酸",
      "name_en": "Aperol Sour",
      "category": "short_drink",
      "price": 48,
      "base_tags": ["base_sour"],
      "flavor_tags": ["orange"],
      "strength": "strength_mid",
      "radar": {"sour": 3, "sweet": 2, "bitter": 1, "strong": 2, "fruity": 3},
      "description": "落日色的橙香酸酒，清爽不重口，颜值和味道一样能打。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "daiquiri",
      "name": "大吉利",
      "name_en": "Daiquiri",
      "category": "short_drink",
      "price": 48,
      "base_tags": ["base_sour"],
      "flavor_tags": ["lime"],
      "strength": "strength_mid",
      "radar": {"sour": 4, "sweet": 2, "bitter": 0, "strong": 3, "fruity": 2},
      "description": "朗姆酒的甘蔗甜和青柠的酸冽，简单直接，海明威的最爱。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "thai_daiquiri",
      "name": "泰式大吉利",
      "name_en": "Thai Daiquiri",
      "category": "short_drink",
      "price": 58,
      "base_tags": ["base_sour"],
      "flavor_tags": ["lemongrass", "pineapple", "lime"],
      "strength": "strength_mid",
      "radar": {"sour": 4, "sweet": 3, "bitter": 0, "strong": 3, "fruity": 4},
      "description": "热带香料和菠萝一起低声哼着泰国小调，酸爽中带着南洋的风。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "gimlet",
      "name": "琴蕾",
      "name_en": "Gimlet",
      "category": "short_drink",
      "price": 48,
      "base_tags": ["base_sour"],
      "flavor_tags": ["lime"],
      "strength": "strength_mid",
      "radar": {"sour": 5, "sweet": 1, "bitter": 0, "strong": 3, "fruity": 2},
      "description": "尖锐的酸，金酒的植物香，干净利落，专治味觉疲劳。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "yuzu_gimlet",
      "name": "白柚琴蕾",
      "name_en": "Yuzu Gimlet",
      "category": "short_drink",
      "price": 58,
      "base_tags": ["base_sour"],
      "flavor_tags": ["yuzu", "lime"],
      "strength": "strength_mid",
      "radar": {"sour": 3, "sweet": 2, "bitter": 2, "strong": 3, "fruity": 4},
      "description": "柚子果肉爆开的瞬间，龙胆的微苦让甜变得高级，东方美学。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "white_lady",
      "name": "白色佳人",
      "name_en": "White Lady",
      "category": "short_drink",
      "price": 48,
      "base_tags": ["base_sour"],
      "flavor_tags": ["orange", "lime"],
      "strength": "strength_mid",
      "radar": {"sour": 3, "sweet": 2, "bitter": 0, "strong": 3, "fruity": 3},
      "description": "像一位穿白色晚礼服的女士，柑橘香气是她的香水，优雅绵密。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "margarita",
      "name": "玛格丽特",
      "name_en": "Margarita",
      "category": "short_drink",
      "price": 48,
      "base_tags": ["base_sour"],
      "flavor_tags": ["lime"],
      "strength": "strength_mid",
      "radar": {"sour": 3, "sweet": 1, "bitter": 1, "strong": 3, "fruity": 2},
      "description": "盐边是眼泪，青柠是思念，龙舌兰是那个叫玛格丽特的女人。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "m30_rain",
      "name": "M30-雨",
      "name_en": "M30-Rain",
      "category": "short_drink",
      "price": 58,
      "base_tags": ["base_floral"],
      "flavor_tags": ["grapefruit"],
      "strength": "strength_mid",
      "radar": {"sour": 2, "sweet": 3, "bitter": 1, "strong": 2, "fruity": 4},
      "description": "坂本龙一在杯子里下了一场雨，朦胧微甜，湖蓝色的液面像在琴键上荡漾。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "little_wing",
      "name": "小翅膀",
      "name_en": "Little Wing",
      "category": "short_drink",
      "price": 48,
      "base_tags": ["base_floral"],
      "flavor_tags": ["elderflower", "orange"],
      "strength": "strength_mid",
      "radar": {"sour": 1, "sweet": 3, "bitter": 1, "strong": 2, "floral": 4},
      "description": "龙舌兰长出了接骨木花的小翅膀，飞在橙子香甜的云朵里。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "dry_martini",
      "name": "干马天尼",
      "name_en": "Dry Martini",
      "category": "short_drink",
      "price_range": [48, 98],
      "base_tags": ["base_deep"],
      "flavor_tags": [],
      "strength": "strength_high",
      "radar": {"sour": 1, "sweet": 1, "bitter": 1, "strong": 5, "fruity": 1},
      "description": "凛冽、辛辣、纯粹，一杯属于狠人的酒，金酒爱好者的终极信仰。",
      "volume": "约 100ml",
      "glass": "martini"
    },
    {
      "id": "green_grape_martini",
      "name": "青提马天尼",
      "name_en": "Green Grape Martini",
      "category": "short_drink",
      "price": 58,
      "base_tags": ["base_floral"],
      "flavor_tags": ["green_grape"],
      "strength": "strength_mid",
      "radar": {"sour": 1, "sweet": 3, "bitter": 0, "strong": 3, "fruity": 5},
      "description": "一口咬下清透的青提，汁水在舌尖炸开，然后金酒的辛香优雅收尾。",
      "volume": "约 120ml",
      "glass": "martini"
    },
    {
      "id": "appletini",
      "name": "苹果马天尼",
      "name_en": "Appletini",
      "category": "short_drink",
      "price": 58,
      "base_tags": ["base_floral"],
      "flavor_tags": ["apple"],
      "strength": "strength_mid",
      "radar": {"sour": 2, "sweet": 4, "bitter": 0, "strong": 2, "fruity": 5},
      "description": "清脆的青苹果糖在嘴里化开，甜得刚刚好，像咬了一口秋天的果实。",
      "volume": "约 120ml",
      "glass": "martini"
    },
    {
      "id": "mumtini",
      "name": "菊花马天尼",
      "name_en": "Mumtini",
      "category": "short_drink",
      "price": 58,
      "base_tags": ["base_floral"],
      "flavor_tags": ["chrysanthemum"],
      "strength": "strength_mid",
      "radar": {"sour": 1, "sweet": 2, "bitter": 1, "strong": 3, "floral": 5},
      "description": "杭白菊的清香在金酒的植物园里散步，干净、雅致、余韵悠长。",
      "volume": "约 120ml",
      "glass": "martini"
    },
    {
      "id": "cedartini",
      "name": "雪松马天尼",
      "name_en": "Cedartini",
      "category": "short_drink",
      "price": 58,
      "base_tags": ["base_deep"],
      "flavor_tags": ["pine"],
      "strength": "strength_mid",
      "radar": {"sour": 1, "sweet": 1, "bitter": 2, "strong": 3, "woody": 4},
      "description": "像走进一座冬天的松林，冷冽的松木香扑面而来，沉稳有力。",
      "volume": "约 100ml",
      "glass": "rocks"
    },
    {
      "id": "smoketini",
      "name": "烟熏马天尼",
      "name_en": "Smoketini",
      "category": "short_drink",
      "price": 58,
      "base_tags": ["base_deep"],
      "flavor_tags": ["smoky"],
      "strength": "strength_high",
      "radar": {"sour": 1, "sweet": 1, "bitter": 2, "strong": 4, "smoky": 5},
      "description": "篝火在杯子里燃烧，阿贝的泥煤烟熏是冬天的暖炉，一口就记住。",
      "volume": "约 100ml",
      "glass": "rocks"
    },
    {
      "id": "paper_plane",
      "name": "纸飞机",
      "name_en": "Paper Plane",
      "category": "short_drink",
      "price_range": [48, 68],
      "base_tags": ["base_sour"],
      "flavor_tags": ["orange"],
      "strength": "strength_mid",
      "radar": {"sour": 2, "sweet": 2, "bitter": 3, "strong": 3, "fruity": 2},
      "description": "苦甜各半，柑橘和草药在空中画弧线，像一架纸飞机优雅着陆。",
      "volume": "约 120ml",
      "glass": "coupe"
    },
    {
      "id": "naked_and_famous",
      "name": "一脱成名",
      "name_en": "Naked and Famous",
      "category": "short_drink",
      "price": 48,
      "base_tags": ["base_deep"],
      "flavor_tags": ["smoky", "herbal"],
      "strength": "strength_mid",
      "radar": {"sour": 2, "sweet": 1, "bitter": 2, "strong": 3, "smoky": 4},
      "description": "梅斯卡尔的烟熏感是主角，草本风味在后台伴舞，名字和味道一样有戏。",
      "volume": "约 100ml",
      "glass": "rocks"
    },
    {
      "id": "last_word",
      "name": "遗言",
      "name_en": "Last Word",
      "category": "short_drink",
      "price": 68,
      "base_tags": ["base_deep"],
      "flavor_tags": ["black_cherry", "herbal"],
      "strength": "strength_mid",
      "radar": {"sour": 2, "sweet": 2, "bitter": 2, "strong": 3, "fruity": 3},
      "description": "黑樱桃的甜和荨麻的苦在舌尖上告别，复杂得像最后一句遗言。",
      "volume": "约 100ml",
      "glass": "coupe"
    },
    {
      "id": "yuzu_negroni",
      "name": "柚子尼格罗尼",
      "name_en": "Yuzu Negroni",
      "category": "short_drink",
      "price": 58,
      "base_tags": ["base_deep"],
      "flavor_tags": ["yuzu", "bitter"],
      "strength": "strength_mid",
      "radar": {"sour": 1, "sweet": 2, "bitter": 4, "strong": 3, "fruity": 3},
      "description": "亚洲第一的配方，柚子的清香让尼格罗尼的苦变得温柔，苦甜交织的成人味。",
      "volume": "约 100ml",
      "glass": "rocks"
    },
    {
      "id": "manhattan",
      "name": "曼哈顿",
      "name_en": "Manhattan",
      "category": "short_drink",
      "price": 48,
      "base_tags": ["base_deep"],
      "flavor_tags": [],
      "strength": "strength_high",
      "radar": {"sour": 1, "sweet": 2, "bitter": 2, "strong": 5, "fruity": 1},
      "description": "黑麦威士忌的辛辣和甜味美思的温柔拥抱，强劲深邃，男人的马天尼。",
      "volume": "约 100ml",
      "glass": "rocks"
    },
    {
      "id": "aviation",
      "name": "飞行",
      "name_en": "Aviation",
      "category": "short_drink",
      "price": 58,
      "base_tags": ["base_floral"],
      "flavor_tags": ["violet", "black_cherry"],
      "strength": "strength_mid",
      "radar": {"sour": 2, "sweet": 3, "bitter": 0, "strong": 2, "floral": 5},
      "description": "灰蓝色的液体像暮色天空，紫罗兰花香和甜樱桃带你飞行。",
      "volume": "约 120ml",
      "glass": "coupe"
    }
  ]
};

module.exports = barData;
